//! Track 6 sub-task 3b — server-side spell table.
//!
//! Mirror of the subset of `SpellDefinitions.ALL` the server needs to
//! process damage and heal spells. Generated by
//! `Project_Dawn/tools/export_spells.gd`; the file is embedded at
//! compile time and parsed once on first lookup.
//!
//! Out of scope (still client-side until sub-task 4 ports buff state):
//! HoT / DoT / CC / port / song / stat-buff / damage-shield / dispel /
//! pet / charm. Spells with those mechanics have only their damage /
//! heal component applied server-side; the rest fires client-local.

use serde::Deserialize;
use std::collections::HashMap;
use std::sync::OnceLock;

const SPELLS_TOML: &str = include_str!("../../data/spells.toml");

#[derive(Debug, Deserialize)]
struct SpellsFile {
    #[serde(rename = "spell")]
    spells: Vec<Spell>,
}

#[derive(Debug, Clone, Deserialize)]
#[allow(dead_code)] // cast_time + cooldown + classes consumed in later sub-tasks
pub struct Spell {
    pub name: String,
    pub target_type: String,
    pub damage_type: String,
    pub base_damage: f32,
    pub heal_amount: f32,
    pub mana_cost: f32,
    #[serde(default)]
    pub hp_cost: f32,
    pub cast_time: f32,
    pub cooldown: f32,
    #[serde(default)]
    pub aoe_radius: f32,
    #[serde(default = "default_min_level")]
    pub min_level: i32,
    #[serde(default)]
    pub classes: Vec<String>,
}

fn default_min_level() -> i32 { 1 }

fn spells() -> &'static HashMap<String, Spell> {
    static SPELLS: OnceLock<HashMap<String, Spell>> = OnceLock::new();
    SPELLS.get_or_init(|| {
        let parsed: SpellsFile = toml::from_str(SPELLS_TOML)
            .expect("spells.toml must parse — fix the embedded file or re-run tools/export_spells.gd");
        parsed
            .spells
            .into_iter()
            .map(|s| (s.name.clone(), s))
            .collect()
    })
}

/// Look up a spell by its canonical name (matches `SpellData.spell_name`
/// on the client). Returns `None` for unknown spells — the client may
/// have a spell the server's table doesn't, in which case the server
/// rejects the cast (logged at debug level).
pub fn lookup(name: &str) -> Option<&'static Spell> {
    spells().get(name)
}

/// Map a damage_type string from the TOML onto the wire enum. The
/// `Hit` broadcast carries this so peers render the right color flash.
pub fn parse_damage_type(s: &str) -> protocol::world::DamageType {
    use protocol::world::DamageType;
    match s {
        "FIRE" => DamageType::Fire,
        "ICE" => DamageType::Ice,
        "LIGHTNING" => DamageType::Lightning,
        "ARCANE" => DamageType::Arcane,
        "HOLY" => DamageType::Holy,
        "NATURE" => DamageType::Nature,
        "SPIRIT" => DamageType::Spirit,
        "SHADOW" => DamageType::Shadow,
        "POISON" => DamageType::Poison,
        _ => DamageType::Physical,
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn embedded_toml_parses() {
        let table = spells();
        assert!(!table.is_empty(), "spells.toml produced no entries");
    }

    #[test]
    fn fireball_resolves() {
        let s = lookup("Fireball").expect("Fireball in table");
        assert_eq!(s.target_type, "ENEMY");
        assert_eq!(s.damage_type, "FIRE");
        assert!((s.base_damage - 50.0).abs() < 0.01);
        assert!((s.mana_cost - 30.0).abs() < 0.01);
    }

    #[test]
    fn healing_light_is_self_heal() {
        let s = lookup("Healing Light").expect("Healing Light in table");
        assert_eq!(s.target_type, "SELF");
        assert!((s.heal_amount - 60.0).abs() < 0.01);
    }

    #[test]
    fn complete_heal_is_max() {
        let s = lookup("Complete Heal").expect("Complete Heal in table");
        assert!((s.heal_amount - 9999.0).abs() < 0.01);
    }

    #[test]
    fn damage_type_parser_handles_known_and_unknown() {
        use protocol::world::DamageType;
        assert!(matches!(parse_damage_type("FIRE"), DamageType::Fire));
        assert!(matches!(parse_damage_type("HOLY"), DamageType::Holy));
        assert!(matches!(parse_damage_type("UNKNOWN"), DamageType::Physical));
    }
}
